from abc import ABC, abstractmethod
from typing import Iterator
from os import getenv
import logging

from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI


load_dotenv()

logger = logging.getLogger(__name__)
logging.basicConfig(filename='logs.log', encoding='utf-8')


class APIKeyNotFoundError(Exception):
    """
    Custom error for API key not found
    """
    pass


class AIModelService(ABC):
    """
    Interface to connect to AI models
    """
    @abstractmethod
    def request(self, prompt: str) -> Iterator[str]:
        """
        Method for requesting something from the AI model
        
        Args:
            prompt (str): instruction to be given to the AI
        Returns:
            Iterator[str]: chunks of the AI response
        """
        pass


class AIGeminiService(AIModelService):
    """
    Class to connect to Gemini AI
    """
    def __init__(self, api_key: str, gemini_version: str) -> None:
        """
        Method for initializing instance attributes
        
        Args:
            api_key (str): Access key for using Google AI models
            gemini_version (str): Name of the AI model to be used
        
        Raises:
            APIKeyNotFoundError: if the API key is not found
        """
        self._api_key = api_key
        if not self._api_key:
            raise APIKeyNotFoundError(
                "API_KEY not found. Please set it in your .env file."
                )
        self.gemini_version = gemini_version
        self.connection = None

    def _connect(self) -> ChatGoogleGenerativeAI:
        """
        Initialize and return a connection to the Google Gemini API.
    
        Returns:
            ChatGoogleGenerativeAI: Initialized Gemini model instance
            
        Raises:
            APIKeyNotFoundError: If API_KEY environment variable is not set
        """
        model = ChatGoogleGenerativeAI(
            model=self.gemini_version,
            google_api_key=self._api_key
        )
        return model

    def request(self, prompt: str) -> Iterator[str]:
        """
        Method for requesting something from the AI model.

        Yields chunks of text as they are generated by the model, enabling
        real-time streaming for interactive use.
        
        Args:
            prompt: The input prompt/message for the model
            
        Yields:
            str: Text chunks from the model response
        """
        if not self.connection:
            self.connection = self._connect()
        for chunk in self.connection.stream(prompt):
            if chunk.content:
                yield chunk.content[0]["text"]


def main():
    try:
        API_KEY =  getenv("API_KEY")
        GEMINI_VERSION = "gemini-3.1-flash-lite"
        gemini_service = AIGeminiService(API_KEY, GEMINI_VERSION)
        for chunk in gemini_service.request("olá, Chat. Meu nome é magal."):
            print(chunk, end="")
        print()
    except APIKeyNotFoundError as e:
        logger.exception(e)
        print(f"\033[31m APIKeyNotFoundError: {e}\033[m")
    except Exception as e:
        logger.exception(e)
        print(f"\033[31m Internal server error: {e}\033[m")


if __name__ == "__main__":
    main()