from abc import ABC, abstractmethod
from typing import Iterator
import os
import logging

from dotenv import load_dotenv
from google import genai
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings.fastembed import FastEmbedEmbeddings
from langchain_chroma.vectorstores import Chroma


load_dotenv()

logger = logging.getLogger(__name__)
logging.basicConfig(filename='logs.log', encoding='utf-8', level=logging.INFO)

CHUNK_SIZE = 2000
CHUNK_OVERLAP = 500
API_KEY = os.getenv("API_KEY")
GEMINI_VERSION = "gemini-3.1-flash-lite"
DATABASE_DIR = "database"


class APIKeyNotFoundError(Exception):
    """
    Custom exception for API key not found
    """
    def __init__(self):
        """
        Method for initializing the exception message
        """
        super().__init__("API_KEY not found. Please set it in your .env file.")


class PDFFileNotFoundError(Exception):
    """
    Custom exception for file not found
    """
    def __init__(self, file_path):
        """
        Method for initializing the exception message

        Args:
            file_path (str): Path of the PDF file that was not found
        """
        super().__init__(f"PDF file not found: {file_path}")


class VectorDatabaseError(Exception):
    """
    Custom exception for vector database-related errors
    """
    def __init__(self, *args):
        """
        Method for initializing the exception message

        Args:
            *args: Arguments passed to the base Exception class
        """
        super().__init__(*args)


class VectorDatabaseCreationError(VectorDatabaseError):
    """
    Custom exception for errors occurring during the attempt
    to create the database
    """
    def __init__(self):
        """
        Method for initializing the exception message
        """
        super().__init__("Error while trying to create the database")


class AIModelService(ABC):
    """
    Interface to connect to AI models
    """
    @abstractmethod
    def request(self, prompt: str) -> Iterator[str]:
        """
        Method for requesting something from the AI model

        Args:
            prompt (str): instruction to be given to the AI

        Returns:
            Iterator[str]: chunks of the AI response
        """
        pass

    @abstractmethod
    def close(self) -> None:
        """
        Method for closing the connection with the AI model
        """
        pass

    def __enter__(self):
        """
        Enables use of the class as a context manager (with-statement).
        The connection itself is opened lazily on first use, not here.
        """
        return self

    def __exit__(self, exc_type, exc_value, traceback) -> None:
        """
        Ensures the connection is closed when leaving a with-block,
        even if an exception occurred inside it.
        """
        self.close()


class AIGeminiService(AIModelService):
    """
    Class to connect to Gemini AI
    """
    def __init__(self, api_key: str, gemini_version: str) -> None:
        """
        Method for initializing instance attributes

        Args:
            api_key (str): Access key for using Google AI models
            gemini_version (str): Name of the AI model to be used
        """
        self._api_key = api_key
        self.gemini_version = gemini_version
        self.client = None

        self.__post_init__()

    def __post_init__(self) -> None:
        """
        Checks if the API key is missing

        Raises:
            APIKeyNotFoundError: if the API key is not found
        """
        if not self._api_key:
            raise APIKeyNotFoundError()

    def _connect(self) -> genai.Client:
        """
        Initialize and return a connection to the Google Gemini API.

        Returns:
            genai.Client: Initialized Gemini client instance

        Raises:
            APIKeyNotFoundError: If API_KEY environment variable is not set
        """
        client = genai.Client(api_key=self._api_key)

        return client

    def request(self, prompt: str) -> Iterator[str]:
        """
        Method for requesting something from the AI model.

        Opens a connection if one doesn't exist yet (lazy connection),
        then yields chunks of text as they are generated by the model.

        Args:
            prompt (str): The input prompt/message for the model

        Yields:
            str: Text chunks from the model response
        """
        if not self.client:
            self.client = self._connect()

        stream = self.client.models.generate_content_stream(
            model=self.gemini_version,
            contents=prompt
        )

        for chunk in stream:
            if chunk.text:
                yield chunk.text

    def close(self) -> None:
        """
        Method for closing the connection with the AI model.

        Explicitly closes the underlying HTTP client so its connections
        are properly released, instead of relying on garbage collection.
        """
        if self.client:
            logger.info("Closing connection with Gemini model")
            self.client.close()
            self.client = None


def get_path(file_name: str) -> str:
    """
    Build absolute path relative to the module directory.

    Args:
        file_name (str): Name or relative path of the file/directory

    Returns:
        str: Absolute path to the file/directory
    """
    return os.path.join(
        os.path.dirname(__file__),
        file_name
    )


class FileLoader(ABC):
    """
    Interface for manipulating files
    """
    @abstractmethod
    def loads_file(self):
        """
        Loads information from a file

        Returns:
            List: List of loaded document contents
        """
        pass


class PDFLoader(FileLoader):
    """
    Class to load PDF files
    """
    def __init__(self, file_name):
        """
        Method for initializing instance attributes

        Args:
            file_name (str): Name or relative path of the PDF file to be loaded
        """
        self.filename = file_name

    def loads_file(self):
        """
        Load the PDF document specified during initialization.

        Returns:
            List: List of loaded document pages

        Raises:
            PDFFileNotFoundError: If the PDF file is not found at the expected path
        """
        pdf_path = get_path(self.filename)
        logger.info(f"Loading PDF from: {pdf_path}")

        if not os.path.exists(pdf_path):
            raise PDFFileNotFoundError(pdf_path)

        pdf_loader = PyPDFLoader(pdf_path)
        documents = pdf_loader.load()

        logger.info(f"Successfully  loaded PDF: {len(documents)} pages")

        return documents


class FileSplitter:
    """
    Class to split file contents into smaller chunks
    """
    def __init__(self, file_loader: FileLoader):
        """
        Method for initializing instance attributes

        Args:
            file_loader (FileLoader): instance of a class that implements
                the FileLoader interface, used to load the file's contents
        """
        self.file_loader = file_loader

    def splits_file(self):
        """
        Split documents into smaller chunks for embedding and retrieval.

        Returns:
            List: List of document chunks with preserved metadata
        """
        file_contents = self.file_loader.loads_file()

        splitter = RecursiveCharacterTextSplitter(
            chunk_size=CHUNK_SIZE,
            chunk_overlap=CHUNK_OVERLAP,
            length_function=len,
            add_start_index=True
        )
        chunks = splitter.split_documents(file_contents)

        logger.info(f"Created {len(chunks)} document chunks")

        return chunks


def creates_vector_database(file_chunks) -> None:
    """
    Create a vector database (Chroma) from document chunks using embeddings.

    Args:
        file_chunks (List): List of document chunks to vectorize

    Raises:
        VectorDatabaseCreationError: if the creation of the database fails
    """
    logger.info("\n=== Starting database creation pipeline ===")

    try:
        logger.info("Initializing embeddings...")
        embedding = FastEmbedEmbeddings()

        db_path = get_path(DATABASE_DIR)
        logger.info(f"Creating vector database at: {db_path}")

        Chroma.from_documents(
            documents=file_chunks,
            embedding=embedding,
            persist_directory=db_path
        )

        logger.info("Vector database created successfully!")
        logger.info("=== Database pipeline completed successfully ===")

    except Exception:
        raise VectorDatabaseCreationError()


def main():
    pass


if __name__ == "__main__":
    main()