from abc import ABC, abstractmethod
from typing import Iterator
import os
import logging

from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings.fastembed import FastEmbedEmbeddings
from langchain_chroma.vectorstores import Chroma


load_dotenv()

logger = logging.getLogger(__name__)
logging.basicConfig(filename='logs.log', encoding='utf-8', level=logging.INFO)

CHUNK_SIZE = 2000
CHUNK_OVERLAP = 500
API_KEY = os.getenv("API_KEY")
GEMINI_VERSION = "gemini-3.1-flash-lite"
DATABASE_DIR = "database"


class APIKeyNotFoundError(Exception):
    """
    Custom error for API key not found
    """
    def __init__(self):
        super().__init__("API_KEY not found. Please set it in your .env file.")


class FileNotFoundError(Exception):
    """
    Custom error for file not found
    """
    def __init__(self, file_path):
        super().__init__(f"PDF file not found: {file_path}")


class VectorDatabaseError(Exception):
    """
    Custom exception for vector database-related errors.    
    """
    def __init__(self, *args):
        super().__init__(*args)


class VectorDatabaseCreationError(VectorDatabaseError):
    """
    Custom exception for errors occurring during the attempt 
    to create the database.
    """
    def __init__(self):
        super().__init__("Error while trying to create the database")


class AIModelService(ABC):
    """
    Interface to connect to AI models
    """
    @abstractmethod
    def request(self, prompt: str) -> Iterator[str]:
        """
        Method for requesting something from the AI model
        
        Args:
            prompt (str): instruction to be given to the AI
            
        Returns:
            Iterator[str]: chunks of the AI response
        """
        pass


class AIGeminiService(AIModelService):
    """
    Class to connect to Gemini AI
    """
    def __init__(self, api_key: str, gemini_version: str) -> None:
        """
        Method for initializing instance attributes
        
        Args:
            api_key (str): Access key for using Google AI models
            gemini_version (str): Name of the AI model to be used
        """
        self._api_key = api_key
        self.gemini_version = gemini_version
        self.connection = None
        self.__post_init__()

    def __post_init__(self) -> None:
        """
        Checks if the API key is missing

        Raises:
            APIKeyNotFoundError: if the API key is not found
        """
        if not self._api_key:
            raise APIKeyNotFoundError()

    def _connect(self) -> ChatGoogleGenerativeAI:
        """
        Initialize and return a connection to the Google Gemini API.
    
        Returns:
            ChatGoogleGenerativeAI: Initialized Gemini model instance
            
        Raises:
            APIKeyNotFoundError: If API_KEY environment variable is not set
        """
        model = ChatGoogleGenerativeAI(
            model=self.gemini_version,
            google_api_key=self._api_key
        )
        return model

    def request(self, prompt: str) -> Iterator[str]:
        """
        Method for requesting something from the AI model.

        Yields chunks of text as they are generated by the model, enabling
        real-time streaming for interactive use.
        
        Args:
            prompt: The input prompt/message for the model
            
        Yields:
            str: Text chunks from the model response
        """
        if not self.connection:
            self.connection = self._connect()
        for chunk in self.connection.stream(prompt):
            if chunk.content:
                yield chunk.content[0]["text"]


def get_path(file_name: str) -> str:
    """
    Build absolute path relative to the module directory.
    
    Args:
        file_name: Name or relative path of the file/directory
        
    Returns:
        Absolute path to the file/directory
    """
    return os.path.join(
        os.path.dirname(__file__),
        file_name
    )


class FileLoader(ABC):
    """
    interface for manipulating files
    """
    @abstractmethod
    def loads_file(self):
        """
        loads information from a file
        """
        pass

    @abstractmethod
    def splits_file(self):
        """
        Split documents into smaller chunks for embedding and retrieval.
        
        Args:
            file: List of documents to split
            
        Returns:
            List: List of document chunks with preserved metadata
        """
        pass


class PDFLoader(FileLoader):
    def __init__(self, file_name):
        self.filename = file_name

    def loads_file(self):
        """
        Load PDF document from the default chess.pdf file.
        
        Returns:
            List: List of loaded document pages
            
        Raises:
            FileNotFoundError: If the PDF file is not found at the expected path
        """
        pdf_path = get_path(self.filename)
        logger.info(f"Loading PDF from: {pdf_path}")
        if not os.path.exists(pdf_path):
            raise FileNotFoundError(pdf_path)
        pdf_loader = PyPDFLoader(pdf_path)
        documents = pdf_loader.load()
        logger.info(f"Successfully  loaded PDF: {len(documents)} pages")
        return documents

    def splits_file(self):
        """
        Split documents into smaller chunks for embedding and retrieval.
        
        Args:
            file: List of documents to split
            
        Returns:
            List: List of document chunks with preserved metadata
        """
        file_contents = self.loads_file()
        splitter = RecursiveCharacterTextSplitter(
            chunk_size=CHUNK_SIZE,
            chunk_overlap=CHUNK_OVERLAP,
            length_function=len,
            add_start_index=True
        )
        chunks = splitter.split_documents(file_contents)
        logger.info(f"Created {len(chunks)} document chunks")
        return chunks


def creates_vector_database(file_chunks) -> None:
    """
    Create a vector database (Chroma) from document chunks using embeddings.
    
    Args:
        file_chunks: List of document chunks to vectorize
    
    Raises:
        VectorDatabaseCreationError: if the creation of the database fails
    """
    logger.info("\n=== Starting database creation pipeline ===")
    try:
        logger.info("Initializing embeddings...")
        embedding = FastEmbedEmbeddings()
        db_path = get_path(DATABASE_DIR)
        logger.info(f"Creating vector database at: {db_path}")
        Chroma.from_documents(
            documents=file_chunks,
            embedding=embedding,
            persist_directory=db_path
        )
        logger.info("Vector database created successfully!")
        logger.info("=== Database pipeline completed successfully ===")
    except Exception:
        raise VectorDatabaseCreationError()
    

def main():
    pass


if __name__ == "__main__":
    main()